services:
  backend:
    image: ${PRIVATE_REGISTRY_URL}/tasknest:latest
    ports:
      - "6666:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - AUTH0__Domain=${AUTH0_DOMAIN}
      - AUTH0__Audience=${AUTH0_AUDIENCE}
      - AUTH0__ClientId=${AUTH0_CLIENT_ID}
      - AUTH0__ClientSecret=${AUTH0_CLIENT_SECRET}
      - AUTH0__ApiKey=${AUTH0_API_KEY}
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgis_data:
  pgadmin-data:

