services:
  backend:
    image: ${PRIVATE_REGISTRY_URL}/tasknest:latest
    ports:
      - "6666:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:DefaultConnection=Server=db;Port=5432;Database=tasknest;User Id=tasknest_db_admin;Password=v2BNKVu4nFjLjPhBLEYujtME6NGg2gH7cXwN3W4tXsfVXxtddxSN
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_MONITOR_ONLY_THIS_CONTAINER
      - REGISTRY_USERNAME=${REGISTRY_USERNAME}
      - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
    depends_on:
      - backend

volumes:
  postgis_data:
  pgadmin-data:

