services:
  #  backend:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: nest_backend
  #    ports:
  #      - "${APP_PORT}:${APP_PORT}"
  #    env_file: .env
  #    environment:
  #      POSTGRES_HOST: db
  #      POSTGRES_PORT: 5432
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #      POSTGRES_DB: test_db
  #    depends_on:
  #      - db

  db:
    image: postgis/postgis:latest
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgis_data:
  pgadmin-data:
