services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
