package at.avollmaier.tasknest.todo.data

import java.util.UUID

data class AttachmentDto(
    val name: String,
    val fileName: String,
    val contentType: String,
    val data: ByteArray,
    val todoId: UUID,
) {

    //Equals and hashCode are generated by IntelliJ IDEA - required because of the data field
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as AttachmentDto

        if (name != other.name) return false
        if (fileName != other.fileName) return false
        if (contentType != other.contentType) return false
        if (!data.contentEquals(other.data)) return false
        if (todoId != other.todoId) return false

        return true
    }

    override fun hashCode(): Int {
        var result = name.hashCode()
        result = 31 * result + fileName.hashCode()
        result = 31 * result + contentType.hashCode()
        result = 31 * result + data.contentHashCode()
        result = 31 * result + todoId.hashCode()
        return result
    }
}